### ISSUE TITLE
Refactoring of Buttonlist and Dialogues structure

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#1065]
This is how the buttonlist and dialogues are organized today:

![untitled](https://cloud.githubusercontent.com/assets/3584238/11560649/b916ecd6-99a0-11e5-878d-38934643f5ea.png)

It's all part of the same component `buttonlist`, and dialogues live inside it in the javascript components and, in the DOM and in CSS.

This is what happens in smaller sizes. Dialogues continue to be relative positions:

![untitled copy](https://cloud.githubusercontent.com/assets/3584238/11560774/a37a2586-99a1-11e5-81ca-6ac29e1af320.png)

**The benefits of having such structure are:**

- Super easy to correlate buttons with dialogues. They are initialized in one single place
- Easy to build the controls in the sidebar 

**The bad sides are:**

- Hard to style when everything is relative to the buttonlist
- It's simply not semantic
- Harder to have dialogues without corresponding button
- Deep nested components in Vizabi
- No clear separation of concerns
- Harder to maintain

Since the bad sides outnumber the good ones, I suggest we refactor it in the following way:

We create a separate dom element where all dialogues will live:

![untitled copy 2](https://cloud.githubusercontent.com/assets/3584238/11560934/8c92b576-99a2-11e5-91e9-6236e8a7f20d.png)

It's `absolute` positioned so that no dialogue is depending on position of buttonlist.
In larger screens, the controls container div turns into display:flex and is not positioned absolute anymore. The items that are supposed to be in sidebar become flex items and the items that are dialogues continue to be absolute positioned.

![untitled](https://cloud.githubusercontent.com/assets/3584238/11560639/9c0ab866-99a0-11e5-8565-c9473b74f71b.png)

Many things would have to change for that to happen:

1. The `options` wouldn't contain `buttons` anymore. Instead, we can call it `controls` and use the config both for buttons and dialogues.
2. Add another component for dialogues (or `base/tool` could initialize the individual dialogue components and place it under the correct div)
3. Initialization of buttons would have to be separate from dialogues - separate Vizabi Components.
4. Triggering a dialogue would happen through the event system instead of direct adding/removing classes in buttonlist.
5. Both buttonlist and dialogues would have to listen to responsiveness separately to adjust to sidebar controls.

Thoughts? Questions? @angieskazka @jheeffer

**Comment by angieskazka** [comment]
comments: 

Please elaborate on points 3 and 4: describe in more details the implementation

Folder structure will need to change. now it's `buttonlist/dialogs/`. will need: `buttonlist/` and `dialogs/`

Lets keep the name `dialogs` rather than `dialogues`

We have treemenu and datawarning, which are kind of dialogs too but different. I guess we are coming the 2 types of dialogs: blocking ones (when the background is blurred) and non-blocking ones. In most cases we don't want the blur because we want to make changes and see the effect interactively or interact with many open dialogs at the same time. But sometimes we want to explicitly block all other interaction and show that it's blocked by blurring the background.

**Comment by angieskazka** [comment]
There is more:
the dialogs should have 3 profiles: `popup`, `sidebar`, `moreoptions`
maybe these should be just the classes applied to different divs in every dialog html
 
these should allow to use the same dialog but display different parts of it in respective situations
the moreoptions dialog should be generated for every tool automatically

the questions is: how do we deal with small things like bubble speed slider, which are not dialogs on their own

**Comment by arthurcamara1** [comment]
Not exactly 3 and 4 yet, but I got this in place to show what I mean:

http://jsfiddle.net/84r10e46/5/

Check out the code @angieskazka @jheeffer

**Comment by jheeffer** [comment]
We chatted about this and discussed (among other things) the following:

Combine dialogs and buttonlist in one component 'controls' which dóes have the separation proposed by arthur in his jsfiddle but does not have the architectural separation. Meaning we get both easy communication between dialogs and buttonlist and the benefit of the style-separation.

**Comment by angieskazka** [comment]
i think 'controls' is a crutch, because anything should be able to communicate to anything.
like, we want to be able to toggle buttons and dialogs from other places in vizabi than just themselves
i suggest having buttonlist as one component and every dialog as a component in itself

the communication would go across _root, which is the tool level

**Comment by angieskazka** [comment]
am i missing anything by saying that dialog components should not be encapsulated in an umbrella "dialogs" component?

**Comment by arthurcamara1** [comment]
@angieskazka yes, they need to be encapsulated because there's a common place in the dom for all dialogs. Unless, of course, the tool itself takes care of that with the wrapping did. Then we don't need to encapsulate at all, but the tool would have to initialize one by one (and we would have to keep it configurable from options)

**Comment by angieskazka** [comment]
ok, got it. so, "dialogs" and "buttonlist", but no "controls" which would have both, right?

**Comment by jheeffer** [comment]
@angieskazka I don't see how combining all controls nicely in one component prevents the rest of the system from interacting with it? 
The dialogs and buttonlist are closely related to one another, both in what they do in Vizabi and their interconnectedness. Thus to me it makes sense to combine them. If any other component wants to

**Comment by angieskazka** [comment]
@jheeffer i see your point but still not convinced
* we want less nested hierarchy of components
* we want to separate "dialogs" from "buttonlist", combining them under "controls" sounds like a compromise. don't want
* The dialogs and buttonlist are closely related to one another -- no, because we already have dialogs without buttons and buttons without dialogs. in general the two multiples may or may not have intersection at all
* i will need dialogs that are very independent from buttonlist, like "data warning". so far i had to make dedicated components for such, that sucks

so, let's not have a "controls" component and move on to implementation ;-)

@arthurcamara1 please validate that i'm not very wrong on it

**Comment by jheeffer** [comment]
Hmm, alright, datawarning is a good example of a dialog that is not a control. Then it makes less sense to group them together. Yeah, then I'm on board too.

**Comment by angieskazka** [comment]
:boom:
