### ISSUE TITLE
Text in data warning on mountain charts is truncated

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1069]
**SUMMARY:** Text is truncated

**SEVERITY:**  Minor

**MODULE:** Mountain chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** Develop

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html 
2)	Mountain chart will be loaded
3)	Click data warning
4)	Scroll down
5)	Note that  text is truncated

**ACTUAL RESULTS:**
Text is truncated on data warning pop up

**EXPECTED RESULTS:**
Text should not be truncated

**SCREENSHOT:**

![v0 9 0_17](https://cloud.githubusercontent.com/assets/9950837/11499680/a104e538-9849-11e5-966f-05959f66d480.png)

**Comment by plward11** [comment]
Tested on the following platforms:

- Windows 7 / Chrome 46.0
- Windows 7 / Firefox 42.0
- Mac OS X Yosemite / Chrome 46.0
- Mac OS X Yosemite / Firefox 42.0
- Nexus 5 / Android 6 / Chrome 46.0

**Comment by plward11** [comment]
I remembered to test this on Mac OS X / Safari 8. The fix does not apply to Safari as is. One additional fix is needed.

The Autoprefixer module is currently set to "last 1 version" which uses the current version of most browsers like Safari 9. Safari 9 correctly supports `display: flex;`. Just adding "safari 8" to the list of prefixes does not fix the problem:

```
.pipe(prefix("last 1 version", "> 1%", "ie 8", "ie 7", "safari 8"))
```

From some googling, it turns out that we need to instead use the following syntax to trigger the autoprefixing:

```
.pipe(prefix({
      browsers: ["last 1 version", "> 1%", "ie 8", "ie 7", "safari 8"]
}))
```

Now we should have autoprefixing for Safari 8 and the other browsers in the list.

Just issued a pull request for the above fix.

**Comment by angieskazka** [comment]
i merged and hope it works, we will know later when people with older iOS/browsers will get to test it
otherwise, we don't worry about supporting safari 8 and below, neither any of IE

**Comment by plward11** [comment]
Oh, sorry I needed to clarify my tests. I checked the CSS output of the Autoprefixer for the vendor-specific CSS prefixes in `vizabi.css`. In the old syntax:

```
.pipe(prefix("last 1 version", "> 1%", "ie 8", "ie 7", "safari 8"))
```

did not output the vendor-specific CSS prefixes, like `-ms` for IE8 or -`webkit-flex` that Safari 8 requires.

Switching to the other syntax:

```
.pipe(prefix({
      browsers: ["last 1 version", "> 1%", "ie 8", "ie 7", "safari 8"]
}))
```

does output those vendor-specific CSS prefixes for the older browsers, like `-ms-fill-lower` for Internet Explorer and the `display: -webkit-flex;` attribute that Safari 8 needs.

I tested and confirmed that the flexbox wasn't working for Safari 8 with the old syntax, and it does work for Safari 8 with the new syntax. I did not test it for IE7 or IE8 though. It has been a long time since I've had a machine with those browsers :)

Thanks for letting me know, I won't worry about too much about supporting the older browser versions or IE.
