### ISSUE TITLE
Timeslider or time model failing to dispatch the events correctly (but doing fine if delay introduced)

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#108]
The event system is a mystery for me and something seems to be incorrect   

See the TODOs in TimeSlider.js 

These cases dispatch the `:change` event correctly:   
`setTimeout(function(){  _this.model.time.value = time; },20)`   
`setTimeout(function(){  _this.model.time.snap(); }, 50); `   

These cases fail to dispatch the `:change` event, or the event is being dispatched *before* changes in model took place:   
`_this.model.time.value = time;`   
`_this.model.time.snap();`

the timeouts are of course not necessary otherwise and should be removed

**Comment by arthurcamara1** [comment]
Alright, @angieskazka . Good finding. Like we talked, this happens because the same event is being triggered at the same execution frame, and triggering the same event twice at the same time is blocked by the event system, which is an important mechanism. But I'm certainly going to find a solution for this asap that also doesn't compromise the other optimizations :+1:
