### ISSUE TITLE
v0.9.1_11: No tooltip is available

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1111]
**SEVERITY:**  Minor

**MODULE:** Bubble chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** v0.9.1

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.9.0/preview/bubblechart.html
2)	Bubble chart will be loaded.
3)	Select a bubble and unselect it. Don’t move cursor from the bubble
4)	Note that no tooltip is available as hovering effect

**ACTUAL RESULTS:**
No tooltip is available as hovering effect after unselecting a bubble

**EXPECTED RESULTS:**
Tooltip should be available as hovering effect after unselecting a bubble

**SCREENSHOT:**

![v0 9 1_11](https://cloud.githubusercontent.com/assets/9950837/11621708/b338f104-9ce0-11e5-8d00-1b44a6a2c76d.png)

**Comment by dab2000** [comment]
fixed in #1096

**Comment by angieskazka** [comment]
no, it's still there, on develop

1) hover China
2) zoom in just a bit without hovering off the bubble, zoom out fully
3) select China
4) deselect China
5) china not highlighted

the reason: zoom event has instruction `clearHighlighted()` because when zoomed bubbles run away from the cursor, `mouseout` event is not called... i wonder if there is a better way

**Comment by angieskazka** [comment]
guys, if there won't be any elegant solution (that wouldn't break anything else or cause slowdowns), i think the best way is to let this bug stay =)
