### ISSUE TITLE
I want a gear button in the buttonlist 

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#116]
![image](https://cloud.githubusercontent.com/assets/496398/7555325/938d0b4e-f748-11e4-9baf-5a19dc7b3dd7.png)

That opens the settings panel with all registered "settings-owners"
(so that we can just hide and show buttons as we please on different resolutions and different contexts.
The buttons displayed in list on screen, should be easy to vary, as the user interacts with the tool (like trail button, shouldn't show until something is selected) And a deselect-all button shouldn't show unless, something is selected.

**Comment by angieskazka** [comment]
@olarosling @arthurcamara1 think of a situation: 

On mobile we show OPTIONS, FIND, SIZE, COLOR, AXES (TRAILS and LOCK are hidden because nothing is selected). Now i want to change the X axis indicator, but first want to select something so i don't forget which countries i compare. After something is selected i see TRAILS and LOCK buttons added, but COLOR and AXES are pushed away because not enough space on button list. I get angry because something disappeared and i can never reach it now (i don't know it's in OPTIONS also)  
Suggested:
1. we should never add buttons in the middle, but only in the end, so that they don't push the others
2a. button list can be dragged-scrolled so buttons can be reached (like instagram filters)
2b. or adding a (▼) or (•••) button, to evidently show that we have more
