### ISSUE TITLE
Query-result not from cache if query selects subset of already cached query

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/vizabi#1162]
E.g.

First this query is executed:
```select geo, geo.region, geo.name where geo.cat = 'country'```

This query and it's result are cached.

Then, this query is executed
```select geo, geo.region where geo.cat = 'country'```

Expected behaviour: The result should be gotten from the cache of the previous query
Current behaviour: The query is forwarded to the reader.

This is the case in for example bubblechart.
Solution is to safe the cache in a different way. Probably first by where and group by, then by column so we can have a smarter checking if data is already available.

**Comment by angieskazka** [comment]
That's expected because these are considered different queries (have different select fields)
However i don't see why would the second query be asked in the first place. Only somebody interested in geo.region could request it, but geo.region is already in the hook, so it should be referred to the first request

**Comment by jheeffer** [comment]
Yes, it is expected with current logic, but the logic isn't using the cache in an optimal way. If the data is already in the memory, we shouldn't request it again.

Why the second query is asked in the first place: a hack in color I think (haven't looked into it yet).
