### ISSUE TITLE
Default formatter is not applied for "population"

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1253]
This happens because csv.js has no "population" formatter in reader_info.formatters
Then utils.mapRows is unable use the default formatter from model.js either
Population ends up being a string

![image](https://cloud.githubusercontent.com/assets/3648190/12308517/ec71c8b0-ba45-11e5-9bbf-f7a2b2f73d19.png)

**Comment by jheeffer** [comment]
Ah, that's because there's first a geo-property query. That one doesn't include population. Then the complete csv is loaded and formatted, but only those columns that are present in the query. So not population. When the population-query comes by, the csv is loaded from cache but with the unformatted population-column. So, solution: add per column flag if it's already formatted.

**Comment by angieskazka** [comment]
@jheeffer or: move default formatter to utils instead of model. then it's safe that it will apply
