### ISSUE TITLE
URL link fail: Vizabi on tools page doesn't update URL when indicator is changed

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#1274]
it happens only when data needs to be loaded when changing indicator

1. Open tools page bubble chart https://tools-dev.gapminderdev.org/tools/bubbles
2. Change Y axis to wealth/inequality/gini
3. The picture updates but not the URL 

works as expected on [vanilla vizabi](http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html), so i would blame the tools page

works as expected on tools page if the indicator is already downloaded: change Y axis to "Population"

**Comment by motin** [comment]
I checked this just now. I can reproduce the bug as described. However, do note that changing the Y axis to wealth/inequality/gini a 2nd time results in the desired route change on the tools page.

While I have not yet determined the exact cause, it seems to be due to a race condition within the vizabi's model set, trigger, freeze and unfreeze methods.

> works as expected on vanilla vizabi, so i would blame the tools page

I would not blame the tools js for this, other than changing the timing of events, causing new vectors for this race condition to surface.
The tools js is simply listening to the ‘persistentChange’ change event from vizabi (and will update the url hash when received), but it is not triggered. not even the ‘change’ event is triggered internally in vizabi.

**Comment by angieskazka** [comment]
@motin yes, it should work the second time, because the data will be cached in vizabi and served from cache, which will change timings

**Comment by motin** [comment]
From the limited debugging I did, it seemed like model set triggered a “change” event, which was frozen. Then when it was the unfrozen (thus released/triggered), the "change" event got frozen anew without being unfrozen. 

> @motin yes, it should work the second time, because the data will be cached in vizabi and served from cache, which will change timings

That supports the race-condition-theory. 

Created a new issue for the race-condition. Let's solve it first and then re-visit this issue, which should (but not necessarily will) be solved by then.

**Comment by angieskazka** [comment]
closed because i can not reproduce it any longer
closed as a duplicate of #1321, which still remains open
