### ISSUE TITLE
Movable floating panels

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#129]
Make the color-panel (and other panels) movable, and the position relative to the graph. So that (on a desktop) it can be linked to with a nice position in a graph.
![image](https://cloud.githubusercontent.com/assets/496398/7793812/4b3432dc-02c4-11e5-8f0f-faf0634d6cbf.png)

**Comment by arthurcamara1** [comment]
@IncoCode When you open dialogs with sliders (example: size dialog or more options), we can't drag the slider anymore because the whole dialog is dragged together.

I suggest one of the two solutions:
1. A specific handle to move the panel, similar to the pin icon. The user would only be able to drag the dialog when dragging the handle/button.
2. Stop the event propagation on the sliders. That is a bit harder, or course, since there are multiple types of sliders

Could you look into this? Thanks a lot

**Comment by angieskazka** [comment]
@IncoCode 
1 is better (safer for now and also more straightforward). 
2 might break checkbox and radiobutton controls as it did before. i'm scared it will :)

**Comment by angieskazka** [comment]
@IncoCode, works fine, but no icon is visible

![image](https://cloud.githubusercontent.com/assets/3648190/9526419/85a2970a-4ce9-11e5-88fd-850bc5623876.png)

we don't include font awesome into the package, instead we just provide icons within our code. (these may be taken from font awesome too)

see the example in buttonlist.js:

https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/buttonlist/buttonlist.js#L501-L517

**Comment by angieskazka** [comment]
#439 fixed the icon
