### ISSUE TITLE
Impossible to use dialogs on small-landscape profile when window height is 250px

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1379]
Find dialog is too small
Test configuration: Chrome, Android 6, Nexus 5 

![image](https://cloud.githubusercontent.com/assets/3648190/13460631/16cb9774-e07c-11e5-9340-a1b18b19f354.png)

Test case number: TC31 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/195875?tab=2&run_section_id=175350&executed_case_id=9445896#executed_case_9445896](https://valorsoftware.testlodge.com/projects/15827/runs/195875?tab=2&run_section_id=175350&executed_case_id=9445896#executed_case_9445896)

**Comment by k6Labz** [comment]
@angieskazka 
This issue is also reproduced by clicking "Options" on landscape.

**Screenshot:**
![comment](https://cloud.githubusercontent.com/assets/9950837/13494530/a6acd6ba-e166-11e5-83f2-26b2242e9511.png)

**Comment by angieskazka** [comment]
Adjust dialogs so that they look ok for the viewport height 250px in small-landscape:

![image](https://cloud.githubusercontent.com/assets/3648190/13529574/497f9c2c-e21d-11e5-8911-cfb43bd9a3d1.png)

Decrease top position by 5px
Decrease list height by 10px
Decrease buttons container top and bottom padding by 5+5px

![image](https://cloud.githubusercontent.com/assets/3648190/13529891/c92d1106-e21e-11e5-90fe-5a76375e5aa2.png)


increase the min-height of the options dialog

![image](https://cloud.githubusercontent.com/assets/3648190/13529902/dca9acb2-e21e-11e5-9ce6-8149fb9c74c9.png)

move the buttonlist div in options dialog into content section so that it's scrollable

![image](https://cloud.githubusercontent.com/assets/3648190/13529967/304dfb98-e21f-11e5-93c5-bf95e52f3021.png)

**Comment by angieskazka** [comment]
Pull request #1422: Refactor dialods so that they work on small landscape and use generic resize function instead of its particular implementations
