### ISSUE TITLE
New data: Is it possible to receive negative aid?

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1532]
![snap73](https://cloud.githubusercontent.com/assets/16382915/13918076/8c82193e-ef6d-11e5-92a9-a2485d5d273c.png)

**Comment by TValeriy** [comment]
![snap74](https://cloud.githubusercontent.com/assets/16382915/13918117/dd780e02-ef6d-11e5-9c34-7dc640586f6d.png)

**Comment by jheeffer** [comment]
Happens quite some times indeed.
([source](https://docs.google.com/spreadsheets/u/1/d/1spkfWDNvN6dN6JFqSsHmSp1G_hHqT5mt7fCpcC4N5TA/pub) and [ddf](https://github.com/semio/ddf--gapminder_world/blob/master/output/ddf--datapoints--aid_received_total_us_inflation_adjusted--by--geo--time.csv#L219)

**Comment by mattiaslindgren** [comment]
https://datahelpdesk.worldbank.org/knowledgebase/articles/114966-why-do-some-countries-receive-negative-amounts-of

**Why do some countries receive negative amounts of aid?
**
Aid and aid per capita data show the net value of official development assistance (ODA). Thus, if countries pay back more than they receive, they can show negative values of net aid. Please note that net aid does not include aid provided to other countries. For example, donor countries such as United States and Canada show ".." for aid per capita rather than negative values because they do not receive official aid. Donor aid provided is tracked separately and published in the World Development Indicators (WDI) online tables and database.

**Comment by angieskazka** [comment]
@mattiaslindgren can we add this answer to the "about" tab of the data in google docs?

**Comment by mattiaslindgren** [comment]
Yes. I did not write it, it is copied pasted from the world bank page linked above.
