### ISSUE TITLE
The ordering of region did not display according to the sorting order of region in stack  

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#1613]
**SEVERITY:**  Minor

**MODULE:**  Mountain Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/mountain 
2) Mountain Chart will be loaded.
3) Click on stack 
4) Click on region radio button placed above the merge mountain 
5) Click on world radio button placed below the merge mountain 
6) Select all the regions 

**ACTUAL RESULTS:**
After selecting the region the sorting of regions displayed adjacent to mountain is not same as its sorting is displayed in the stack 

**EXPECTED RESULTS:**
The regions should be displayed in sorting order as same as in stack 

**SCREENSHOT:**

![5apr_order](https://cloud.githubusercontent.com/assets/9950837/14279926/260dd020-fb49-11e5-8129-b4229996bc08.png)

**Comment by angieskazka** [comment]
@sergey-filipenko it's a bit out of scope because "Stacking order" is not applicable when there is no stacking by regions. The list to the left is correct (it corresponds to the max height of the mountains top to bottom). The list to the right is also correct but you can't see it unless you stack them on top of each other. I suggest disabling the "manual sorting" control when "stack" radio button is not in the "world" position

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1621
