### ISSUE TITLE
Incorrect info about vizabi version

### ISSUE THREAD

**Issue by TValeriy** [Gapminder/vizabi#1616]
![screen shot 2016-04-06 at 09 25 12](https://cloud.githubusercontent.com/assets/16382915/14307699/b9bfd936-fbd9-11e5-87a1-b0fd1604fe45.png)

**Comment by angieskazka** [comment]
Current method: we append vizabi.js by the footer:
var version = ';(function (Vizabi) {Vizabi._version = "' + pkg.version + '"; Vizabi._build = "' + timestamp.valueOf() + '";})(typeof Vizabi !== "undefined"?Vizabi:{});

this is wrong because Vizabi is not defined on tools page. Neither it is good to let external page manipulate internal variables.

So we need to inject version number internally, into vizabi code.
I was looking into `replacement` methods with gulp and i'm still confused

the best method is to use [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace)
the syntax is straightforward but the values remain unchanged, and there is no feedback
i have no idea how i can debug it or verify it's working at all

here is what i tried
```
var replace = require('rollup-plugin-replace'); 

rollup.rollup({
      entry: './' + path.join(config.src, entryFile),
      resolveId: resolvePath,
      plugins: [
        replace({
           GULP_REPLACE_VERSION:  pkg.version
           GULP_REPLACE_BUILD:  timestamp.valueOf()
        })
      ]
    }).then(function(bundle) {
```


Another method i tried is using [gulp-replace](https://www.npmjs.com/package/gulp-replace)
```
var replace = require('gulp-replace'); 
...
.pipe(replace("GULP_REPLACE_VERSION", pkg.version))
.pipe(replace("GULP_REPLACE_BUILD", timestamp.valueOf()))
```

(see the commit 1978c7db0345b814c832a8c8e4495c75ef26cb7a)
but i could only make it work with gulp build, because it has these pipes
i couldn't make it with gulp dev, which is more important

**Comment by TValeriy** [comment]
Retested. Fixed. 

![snap116](https://cloud.githubusercontent.com/assets/16382915/14519167/bfe210de-0225-11e6-8343-18cf2d60497a.png)
