### ISSUE TITLE
Charts do not update language strings when language changes

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#222]
in gapminder.js there are 2 languages now
but when i switch language only button list and dialogs change strings

i am trying to add "change:language:id": function (evt) {
listener to bubble chart, but it's never called

(actually none of the events i am listening to is being called)

@arthurcamara1 please take a look (or tell me if i'm doing it wrong)

![image](https://cloud.githubusercontent.com/assets/3648190/8619056/df1d84da-2713-11e5-916b-46ef4963f184.png)

**Comment by arthurcamara1** [comment]
Sure, looking into it now! It's important that the chart changes! :+1:

**Comment by arthurcamara1** [comment]
@angieskazka  Quick solution: call `updateUIStrings` on ready.

Explanation: The event you mentioned `change:language:id` works, but only when data is there already. When new data is loaded, it's not considered to be a "change" (meh) and it's not triggered. 

If you're curious, try this:

```
"change:language:id": function () {
          console.log("LANGUAGE CHANGED");
},
```

And press the language button multiple times. First time it's not called (because it loads new data). It is called the next times. For now, the chart translates. Let's discuss improvements on this approach soon.

**Comment by arthurcamara1** [comment]
Working version: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by angieskazka** [comment]
yes, thank you. one more thing is that the language resets when i refresh the page
is there a reason it's not in the state?

**Comment by arthurcamara1** [comment]
Ok! Added #224 :)
