### ISSUE TITLE
PA_50: “Fullscreen page” link is not working properly.

### ISSUE THREAD

**Issue by SadiaKualitatem** [Gapminder/vizabi#269]
RELEASE: v0.6.0

SEVERITY: Blocker

MODULE: Pop By Age Chart

OS/BROWSER: Win7 / Chrome 45.0
STEPS TO REPRODUCE:
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.6.0/preview/popbyage.html
2)	Pop By Age chart page will be loaded
3)	Click “Fullscreen page” link available on the right side of the page.
4)	Note the behavior of the new page which is stuck in loading 

ACTUAL RESULTS:
New page is opened but there is nothing to show for the user. Page is continuously loading. It shows nothing to the user.

EXPECTED RESULTS:  
After clicking the “Fullscreen page” link the full screen should be shown to the user properly

SCREENSHOT:
![vizabi_pop_by_age_chart_05 1](https://cloud.githubusercontent.com/assets/1772649/8876006/488b409c-3236-11e5-8f10-34382ebd0d54.png)

![vizabi_pop_by_age_chart_05 2](https://cloud.githubusercontent.com/assets/1772649/8876007/48943314-3236-11e5-9d07-55578d10fc7a.png)

**Comment by maximhristenko** [comment]
done this

**Comment by angieskazka** [comment]
fixed

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**RELEASE:** v0.7.0

**DESCRIPTION:** This issue is appeared again, can be seen in below screenshot

**SCREENSHOT:**
![regression_08 1](https://cloud.githubusercontent.com/assets/9950837/9439531/6609b550-4a81-11e5-9012-0566059e8470.png)

![regression_08 2](https://cloud.githubusercontent.com/assets/9950837/9439532/660db3c6-4a81-11e5-9032-4e0434eeed67.png)

**Comment by angieskazka** [comment]
not any longer. all good now
