### ISSUE TITLE
High Definition option on large screen

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#345]
On my huge retina screen: this thing loks great but interaction is very slow. We should probably avoid bringing up the resolution as the processor or graphic card can't really make it happen smoothly.
Can we detect that interaction will be slow and let user actively choose to have higher resolution. Probably better to let users who may want HD for screencapturing, or other reason, give them an option under the settings panel, to increase res.

![image](https://cloud.githubusercontent.com/assets/496398/9283281/de4fb566-42d2-11e5-96e4-7e67a1645516.png)

**Comment by angieskazka** [comment]
@olarosling I suggest let's always run low-res regardless of the screen! i removed the resolution dependency of screen size and replaced it with d3 area.interpolate("basis") so that the graph looks smooth. 

Also when we were making the assets for the video we had unreasonably large number of vertices along xAxis 200, now i put 50 instead.

The rest depends not on us but on Chrome painting methods and videoadapter stuff. Painting time for 1 frame on 320x568 tool size takes 24 ms, while on 1924x1302 it takes 192 ms. The most expensive operation is "rasterize paint", not javascript.

**Comment by angieskazka** [comment]
related to #385
