### ISSUE TITLE
Create a new tool: bubblemap

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#388]
Bootstrap the chart with D3 maps + Google maps

We start from a simple world map with no Zoom and Pan and we aim to replace this one as fast as possible: [gapminder world map](www.gapminder.org/world/#$majorMode=map)
![image](https://cloud.githubusercontent.com/assets/3648190/10161909/96159e7a-66a7-11e5-9fdd-b6177ead464e.png)

The bubble map should look and act like this [ebola example on google public data](http://www.google.com/publicdata/explore?ds=eq10po6kah9si_&ctype=m&strail=false&bcs=d&nselm=s&met_s=cases_cum&scale_s=lin&ind_s=false&ifdim=district&tunit=D&pit=1412892000000&hl=en&dl=en&ind=false&xMax=-5.891764156250019&xMin=-18.94352196875002&yMax=4.0345925292218&yMin=11.99141057995339&mapType=t&icfg=eq10po6kah9si_%253A2%253Adistrict%26%264:-71:-40:%7Ceq10po6kah9si_%253A2%253Adistrict%26%2611:24:-45:&iconSize=0.47)

![image](https://cloud.githubusercontent.com/assets/3648190/10161054/ae32dae6-66a1-11e5-934f-721846af809a.png)

use this tutorial to understand how you can create your own tool in Vizabi
http://www.vizabi.org/blog/2015/07/17/create-your-tool/

watch this d3.js on a Google maps: http://www.youtube.com/watch?v=wqPGFs0cqxI

then the easies way would be to copy the [Bar Chart](https://github.com/Gapminder/vizabi/tree/develop/src/tools/barchart) example and change it so that it becomes Bubble Map. You can also take Bubble Chart of course, but it's way more complicated and you risk to get lost in irrelevant details.

You will need a preloading of Google map (or topo JSON or geo JSON). Look how the preloading is done in Mountain chart tool (see method `afterPreload`) and the relevant configuration in Gapminder.js ([lines 418-427](https://github.com/Gapminder/vizabi/blob/develop/src/vizabi_custom/gapminder.js#L418-L427))

later-later we will do the heatmap layer too ;)
![image](https://cloud.githubusercontent.com/assets/3648190/10161273/1ac60e20-66a3-11e5-97cf-14df236f9ebd.png)

Update:
There is also a previous implementation of a bubble map by Arek here:
https://github.com/amytych/vizabi/tree/feature/map/src/tools/_gapminder/map

This was working before but then we have changed a lot in vizabi core and now it doesn't
One way to solve this issue is to take Arek's code and debug it so that it's working

**Comment by angieskazka** [comment]
Good progress on the tool

the next steps: 

* fix alignment of the bubbles (they are falling off the countries. is the coordinate system of the map json incorrect?)
* add year label
* add controls for color, find, size, expand, present (see bubble and mountain charts)
* remove sqrt scale and keep only linear or log in the state: the reason is to be able to switch between lin and log
* but we still want to control the area, so add functions “areaToRadius” and “radiusToArea” similar to bubble chart, and apply the areaToRadius conversion when you set the bubble radius `"r"`. apply radiusToArea conversion when you set the `range()` of size scale
