### ISSUE TITLE
Add controls to the side on 'large' profile

### ISSUE THREAD

**Issue by arthurcamara1** [Gapminder/vizabi#394]
Change the layout for GW build

**Comment by angieskazka** [comment]
according to the latest discussion with Ola, we should display side controls on large profile because we have lots of space that we don't use.

so, when the profile is `large`, we should stack the hidden dialogs on the right side: 
color, find, size for bubble chart and color, find, stack for mountain chart
(the collection may change)

similar to how people are used to have in Gapminder world http://www.gapminder.org/world/
![image](https://cloud.githubusercontent.com/assets/3648190/10116424/2e36b9fc-6435-11e5-8a5f-60172b3f3725.png)

do as much as possible with SCSS and only apply javascript when necessary

@arthurcamara1 please point out which SCSS files to hack and where possible JS would fall appropriate

**Comment by arthurcamara1** [comment]
In order to do this, we need to make `buttonlist` configurable in UI options of any chart.

**Currently**, the `ui` options object for a chart that shows the buttons/dialogs `find`, `color`, `size`, in that order, is:

```javascript
ui: {
    buttons: [ 'find', 'color', 'size']
}
```

It will render something like this:

![screen shot 2015-09-28 at 2 42 28 pm](https://cloud.githubusercontent.com/assets/3584238/10135584/7dc6af2a-65ef-11e5-852d-a9c5ddd15864.png)

In case we wanted the controls to be on the side (on large profile only), maybe in a different order, we could do it like this:

```javascript
ui: {
    buttons: [ 'color', 'find', 'size']
    buttons_expand: true
}
```

And something like this would be rendered on large screen:

![screen shot 2015-09-28 at 2 42 32 pm](https://cloud.githubusercontent.com/assets/3584238/10135634/d05e24a2-65ef-11e5-9e52-e1155ea2c38a.png)

And in medium and small screens, the same old buttonlist would prevail.

Now, if we wanted to only expand one of the buttons, we could:

```javascript
ui: {
    buttons: [ 'find', 'color', 'size']
    buttons_expand: [ 'find' ]
}
```
![screen shot 2015-09-28 at 2 42 38 pm](https://cloud.githubusercontent.com/assets/3584238/10135784/fa85277a-65f0-11e5-834b-173f8ad6e6e0.png)

**How to solve it**

Assuming the strategy above, the most straightforward way to solve it is with simple CSS classes. 

If you go to the file [src/components/_gapminder/buttonlist/buttonlist.js](https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/buttonlist/buttonlist.js#L243), you will see that each button and each dialog is added dynamically according to the configuration received by `options.ui.buttons`.

At that point, you can check `ui.buttons_expand` and add a class to each button and dialog that should be expanded: `vzb-dialog-side` , for instance.

Then, you edit [src/components/_gapminder/buttonlist/buttonlist.scss](https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/buttonlist/buttonlist.scss) to hide each button that has that `vzb-dialog-side` class, and display each dialog that has `vzb-dialog-side` class with `display: block; position: static`. It should happen, of course, only [in case the screen is large](https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/buttonlist/_buttonlist.scss#L103).

**Comment by angieskazka** [comment]
Comments and improvements

**Initial appearance (urgent by wednesday)**
When opening on the large profile, we can see the image like this 

![image](https://cloud.githubusercontent.com/assets/3648190/10277322/90b61d26-6b55-11e5-84a9-fa0438b36113.png)

but we actually want to have it like this already from the start with no need to click the buttons
![image](https://cloud.githubusercontent.com/assets/3648190/10277343/b02f61a8-6b55-11e5-9e94-18b1cb64ba97.png)

i think it is a bug because the ui.buttons_expand is set correctly, as i can see on this breakpoint in buttonlist:

![image](https://cloud.githubusercontent.com/assets/3648190/10277423/197f6f40-6b56-11e5-905d-069b21bfadcd.png)

***

**Order of panels (not as urgent)**
By clicking the buttons and opening panels i couldn't get panels in the order of `this.model.ui.buttons_expand = ["colors", "find", "size"]`despite the array is set correctly. The ui.buttons order is prioritised instead. Panels should obey the order in `this.model.ui.buttons_expand`

***

**Styling (not as urgent)**

Continue hacking of the styles. We don't need the impression of panels being separate dialogs, they should rather form a single sidebar. 

![image](https://cloud.githubusercontent.com/assets/3648190/10277639/8bd1e194-6b57-11e5-9ecf-c0e01deb6b74.png)

Start by removing the box-shadow

![image](https://cloud.githubusercontent.com/assets/3648190/10277662/b6bbbce0-6b57-11e5-87ce-6172cae43a54.png)

Change the background to match the button pane. Use color `$vzb-color-primary-lightest`

Hide OK buttons (we don't want to close the panels ever :-D )

Change title and indicator selector divs to inline. You might need to take indicator selector divs out of "content" container. Just make a new container "inlinable". Put there indicator selectors and search box :)

Put buttonlist below the panels

If we open more dialogs than the ones in the list of `buttons_expand`, let them open next to the side bar, not inside the side bar

The result picture should look like this

![image](https://cloud.githubusercontent.com/assets/3648190/10278060/a5a525a6-6b5a-11e5-944c-e159dd2563cd.png)

**Comment by angieskazka** [comment]
Done. The improvements are taken as new issues #601 #602 #603 #604 #605
