### ISSUE TITLE
v0.7.0_04: Chart is disturbed by changing the orientation

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#407]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**PLATFORM:** Windows 7 / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click on the full screen button under RESPONSIVENESS
4)	Click play button
5)	Click Portrait view before stopping the movement of the slider ball
6)	Chart view is changed to Portrait view
7)	Slider ball is stopped
8)	Note that chart is disturbed after changing the orientation

**ACTUAL RESULTS:**
Chart is disturbed by changing the orientation from full screen to portrait view

**EXPECTED RESULTS:** 
Chart should not be disturbed by changing the orientation
 
**SCREENSHOT:** 
![vizabi_bubble_chart_04 1](https://cloud.githubusercontent.com/assets/9950837/9492798/57c574d6-4c14-11e5-8608-7a43641ea1c3.png)

![vizabi_bubble_chart_04 2](https://cloud.githubusercontent.com/assets/9950837/9492799/57c83176-4c14-11e5-9fb1-c5d951d58f36.png)

**Comment by angieskazka** [comment]
WHERE: 
the problem is within BubbleChart component, see bubblechart-component.js

The events are produced here:
L81      'change:time:value': function () {
L375     this.on("resize", function () {

![image](https://cloud.githubusercontent.com/assets/3648190/9519208/0216540c-4cbd-11e5-9724-7955245ceea0.png)

As you can see, the events are correct, but the effect is wrong.

Each of the events ('change:time:value' and "resize") is working correctly when on it's own, also the zoom feature works when on it's own

SOLUTIONS:
you'll need to discover the interplay between the two events AND ZOOM FEATURE, and resolve it in such a way that nothing else breaks. Most likely, the zoom function is called with wrong parameters or old parameters...

EXTRA:
you may also test the interplay of other events, like trying all the crazy stuff while time is playing

**Comment by angieskazka** [comment]
the above fixed the issue

**Comment by angieskazka** [comment]
@k6Labz please check the develop if the issue still persists
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html

**Comment by k6Labz** [comment]
Retest Result: Passed 
Environment: Develop branch - http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
