### ISSUE TITLE
v0.7.0_19: Chart is disturbed

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#423]
**SEVERITY:** Critical

**MODULE:** Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0
* Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/barchart.html 
2)	Bar chart page will be loaded
3)	Click the “Axes” option
4)	Select  “Time” from first drop down under X-axis
5)	Click “ok”
6)	Click full screen button under RESPONSIVENESS 
7)	Note that chart is disturbed

**ACTUAL RESULTS:**
Chart is disturbed 

**EXPECTED RESULTS:** 
Chart should not be disturbed in any case

**SCREENSHOT:** 
![vizabi_bar_chart_04](https://cloud.githubusercontent.com/assets/9950837/9493538/c094479e-4c19-11e5-88bc-1d26e59695e0.png)

**Comment by arthurcamara1** [comment]
Hi @k6Labz Many of the issues reported all related to Bar Chart changing xScale to Time. But then having multiple issues for that causes more confusion than clarity in my opinion. If just changing the axis to time is buggy, then many things will of course break. Should we really post one issue for all subsequent that break? Maybe we shouldn’t need 10 issues about those, because fixing one will fix all

Opinions?

**Comment by k6Labz** [comment]
Hi @arthurcamara1 
Thanks for your comment, next time whenever we have such sort of issue we will make it generic. if there's other issue related to it, only one issue will logged on Github as per your suggestion
