### ISSUE TITLE
v0.7.0_30:  Irregular shape of the scale is there

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#454]
**SEVERITY:** Minor

**MODULE:** 
* Pop By Age Chart
* Mountain Chart
* Bar Chart

**PLATFORM:**
* Windows 7 / Chrome 45.0
* MAC / Safari 8.0
* Android Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/popbyage.html 
2)	Pop By Age chart page will be loaded
3)	Click the colors option
4)	Click first dropdown
5)	Select “Life expectancy” and notice its color scale shape
6)	Now select “GDP Per Capita” 
7)	Note that the color scale is of irregular shape

**ACTUAL RESULTS:**
Irregular shape of the scale is there under “GDP Per Capita”

**EXPECTED RESULTS:** 
Color scale shape should be same 

**SCREENSHOT:**
![vizabi_pba_chart_03 1](https://cloud.githubusercontent.com/assets/9950837/9572533/27b37310-4fca-11e5-96f6-0bcacf95a667.png)

![vizabi_pba_chart_03 2](https://cloud.githubusercontent.com/assets/9950837/9572532/27b0cfac-4fca-11e5-87cd-30d43141298f.png)

**Comment by angieskazka** [comment]
@IncoCode removing one color stop was not correct in #472. palettes may have as many color stops as they like. The correct solution would be to check if the constants in this line are valid:

```
this.rainbowEl.classed("vzb-hidden", false)
          .style("height", (utils.keys(palette).length * 25 + 5) + "px")
```

https://github.com/Gapminder/vizabi/blob/develop/src/components/_gapminder/colorlegend/colorlegend.js#L133

they are probably not. You'll need to measure the actual height of the lines (it will be different on different os) and adjust the gradient height to the height of the list

alternatively you can manually set the list line spacing so that it has the same constants
