### ISSUE TITLE
Client-side interpol support three methods

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#493]
To allow smaller datasets, we can skip interpolation in the back end, and make it happen in the front end. But to do this right, we need to support three types of interpolations: Linear, Growth and Log. They will be decorations on the indicator metadata. Which one to use, depends on the indicator. E.g TFR use Linear, while "GDP per cap" uses growth.

**Comment by angieskazka** [comment]
growth interpolation looks like a slightly larger task

http://stackoverflow.com/a/14163874/3673369
i wouldn’t want to run this for every value between the years
too much computation.

instead, the lean file should be received, then time keyframes in data should be prefilled by this heavier computation, then during dragging and playing i suggest we only rely on linear interpolation (or no interpolation during play, since we know keyframes are prefilled)

even more file space we can save if we interpolate PROPERTIES as well (i.e. swe has a geo.region=“eur” until stated differently in some year, then that value until next change and so on)

**Comment by angieskazka** [comment]
Vizabi now supports different interpolators and i added exp interpolation to the collection.

```
        linear: function(x1, x2, y1, y2, x){
            return +y1 + (y2 - y1) * (x - x1) / (x2 - x1);
        },
        exp: function(x1, x2, y1, y2, x){
            return Math.exp((Math.log(y1) * (x2 - x) - Math.log(y2) * (x1 - x)) / (x2 - x1));
        },
```
the `exp` interpolation follows the model y = Neˆ(kx), read the manual here:
http://www.oakton.edu/user/2/somplski/c170/online/math/1/mp1m.htm

in order to use it you need to specify it in the metadata for indicators: 
```
        "gdp_per_cap": {
            "allowCharts": ["*"],
            "use": "indicator",
            "unit": "gdp_per_cap",
            "interpolation": "exp",
            "scales": ["log", "linear"],
        },
```
