### ISSUE TITLE
dragging panel is a jumpy ride

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#501]
When I use the small hand icon to drag the panel around, it keeps bouncing under my cursor. Should you just turn animation of maybe?
![image](https://cloud.githubusercontent.com/assets/496398/9808404/01cbc862-585f-11e5-8351-a634c046cfc8.png)

**Comment by angieskazka** [comment]
Steps to reproduce: 
open any dialog, 
drag a little, 
pin it, 
interact outside the dialog so that the dialog sticks to the edge, 
drag dialog again. 
Expected same smoothness as it was on the first drag, but animation hinders it. 

Unpin. 
Try to drag again. Still jumpy interaction

Close dialog and open it again. 
Now interaction is smooth as at first time!

@IncoCode
