### ISSUE TITLE
v0.7.1_02: Countries are still selected for no bubbles by changing  the axis options

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#503]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 41.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/bubblechart.html 
2)	Bubble chart page will be loaded
3)	Click any bubble representing a country
4)	Click the “X and Y”
5)	Click first drop down under X axis
6)	Select first option from the list which is “Child survival”
7)	Click ok
8)	Note that all the bubbles are disappeared and the selected countries name are still there without any bubble
9)	Also note that when we click play, only selected bubbles are displayed with disturbed line

**ACTUAL RESULTS:**
All the bubbles are disappeared by changing scale from axis and the selected countries names are still there without any bubble 

**EXPECTED RESULTS:** 
Countries should be unselected if there is no bubble for any country

**SCREENSHOT:** 

![vizabi_bubble_chart_02 1](https://cloud.githubusercontent.com/assets/9950837/9815160/66383404-58ad-11e5-8699-f5829eaf9bba.png)

![vizabi_bubble_chart_02 2](https://cloud.githubusercontent.com/assets/9950837/9815161/6640ee5a-58ad-11e5-8523-62334dae8ed3.png)

**Comment by angieskazka** [comment]
ok, so the problem is that the data was not available for child survival
with a604a4a6ffe9f91f0a82cb9d560f155efde305c0 i added metadata info about which charts can use different indicators. Result: you will be only able to see indicators for which we have local data.

this will change when we have fully-working waffle server, but so it is now...

thanks anyway
