### ISSUE TITLE
STAGING ENVIRONMENT // QA that stops this bug for ever coming back

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#553]
Mark this as done, only after  
We've got a QA procedure in place human tests for core interaciotns
so that it guaranteed that commits to Produciton are blocked,
until a human being has tried to select a bubble and drag the label .
:)

**Comment by angieskazka** [comment]
Ola Rosling [9:05 PM] 
Yes!
Because after launching
it's no llonger OK to break the branch in produciton
at all
So it will have to stick around
thanks for reading carefully
:simple_smile:
This means
Fixing problems is going to be way more difficult
exactly based on this kind of experience

Angie [9:06 PM] 
after launching we switch the live page to master branch and only update it when tested, while we continue to hack and break the develop

Ola Rosling [9:07 PM]
Exactly
But we should launch every week
the fixes
So we need a staging environment
ASAP!

**Comment by olarosling** [comment]
And we need a Basic QA manual, that ensure fixes can be quickly done, and QA:ed so that they don't break core functionality.  We probably want a global crew of QA-freelancers that jump in and run over the list as soon as it's requested,... and flag the fixes as : not breaking master's core features.

**Comment by arthurcamara1** [comment]
Vizabi Staging is already in place.
Tools page staging is going to be in place very very soon - @valorkin team
Let's use https://github.com/Gapminder/gapminder-tools-vizabi/issues for this #gapminder-tools-vizabi/46
