### ISSUE TITLE
Setting pane: Hide scroll when content fits

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#560]
![image](https://cloud.githubusercontent.com/assets/496398/10129934/b67aa3fc-65c3-11e5-91ef-3baae4885207.png)

**Comment by angieskazka** [comment]
where to hack:
_dialog.scss (or something)

how to hack
the issue is styling of the container on Windows
especially bad is hiding a scroll bar on Firefox on Windows
requires ugly hacks, like [this one](http://jsfiddle.net/qqPcb/)

see how we did for the buttonlist (you can scroll the buttons but scroll bars do not appear)
