### ISSUE TITLE
Special characters are not supported in build, but supported in dev

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#65]
Even primitive ASCII characters are destroyed when i run Vizabi in build. 

Use cases when i need them: 
* put arrows on buttons in testing preview page UI, like ⇅ and ⇄ 
otherwise i have to write TOP/BOTTOM, LEFT/RIGHT, which is ugly or TB, LR which is both ugly and confusing

* intercept keyboard shortcuts, like [a] equals "a", [shift]+[a] equals "A", that's fine. now [alt]+[shift]+[a] equals "Å", but this shortcut works only in dev, not in build

i spent time trying to find a workaround, but maybe it's just one setting in Grunt, than breaks the thing?

Issue is not very urgent, but please help
It's not blocking me from developing, but is kinda blocking from demoing

@arthurcamara1 @ambodi

**Comment by arthurcamara1** [comment]
@angieskazka Have you tried using HTML codes for those characters instead?
`&#8592;` for &#8592; , etc ? See more here: http://character-code.com/arrows-html-codes.php
Let me know if this helps.

**Comment by arthurcamara1** [comment]
As for the second problem, I'm not sure how you implemented it or if this is what you mean, but you can use the event properties to detect shift and alt. Then I don't see how you would need to check special chars.

Something like this would detect Enter+Shift :
```javascript
if ( event.which == 13 && event.shiftKey ) {
// yay, Enter + Shift are being pressed
}
```

same goes with `altkey` and `ctrlKey`

**Comment by angieskazka** [comment]
1) HTML character codes help somewhat (can place an arrow on a button), until you look at the code later on and be wondering what do they mean. so, one-time solution is ok, but maintainability is very low. I would prefer the production to be displaying things as good as develop.

2) yes, fixed that as you suggest. i had a convenience recognition `(String.fromCharCode(charCode) == "Å")` before, that's why it got screwed up. Now i have `(charCode == 197) // Å`, but again this is worse on readability of the code

**Comment by arthurcamara1** [comment]
Well, you can comment those, as you did, to keep readability. :+1:  But those are quite common practice, since special characters do tend to cause problems when encoding files. I believe `concat` and `min` will always generate UTF-8 encoded files, and that can be the problem in build. We can try to check more on encoding and improve this later.
About the second problem, I did not mean checking for charCode 197 (which is a character produced by this combination according to your computer's configurations). I meant checking for "a" (97, which is a in every keyboard), shift and alt.
Anyways, this is not so important, and I'm glad you got it working :)

**Comment by angieskazka** [comment]
ok
