### ISSUE TITLE
Bad character in title

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#69]
http://bit.ly/1aIDllF

![image](https://cloud.githubusercontent.com/assets/496398/6443083/e2f38382-c0f4-11e4-9b4b-2b21240d3382.png)

**Comment by angieskazka** [comment]
@arthurcamara1, i need help. as discussed before, one of our PROD grunt sequences, probably minification, destroys special characters. See any Portugese "options" button in [any tool](http://bit.ly/1aIDllF):

![image](https://cloud.githubusercontent.com/assets/3648190/6545156/26e709d8-c578-11e4-9ffd-62052e423f25.png) ==> ![image](https://cloud.githubusercontent.com/assets/3648190/6545155/180182ea-c578-11e4-8b85-c4596b209adf.png)

Back to the original issue, as discussed on Stack overflow [here](http://stackoverflow.com/questions/1306838/problem-with-special-characters-when-minifying-js), i am using "\u2013" instead of "–". The result you can see in Ola's post above, so even codes don't help. And if codes would help, you probably don't enjoy writing codes for every special character in portugese.

For now i will just put hyphen " - " as a quick solution in my string

But the problem is rather generic and it blocks us from using typography etiquette, convenience symbols like →, and most important, any language other than english

Could it be that our minifier has some options? Like "special characters" that is set to "off" by default

**Comment by angieskazka** [comment]
the above test is successful
![image](https://cloud.githubusercontent.com/assets/3648190/12579394/ec26dfe4-c427-11e5-9699-559537f9e8cf.png)
