### ISSUE TITLE
Resize can be more economical

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/vizabi#75]
We ask components to resize whenever page is resized. However it's not necessary, we should resize components only if a tool container actually changes its size. 

Minor issue. Hans says in reality resizing happens extremely rare. Usually the initial size stays throughout the entire session

**Comment by arthurcamara1** [comment]
> We ask components to resize whenever page is resized.

Not really. [We only ask `layout` to resize](https://github.com/Gapminder/vizabi/blob/develop/src/base/layout.js#L44) and, in our case, **only tools** have an instance of `base/layout`, which means they are the ones in control.

But you're right that it can be improved. The solution is for `base/layout` to trigger only if REALLY changes the size of the container, and not simply at window resize. In that case it is a minor issue because 99% of times that the browser changes size, it's because the container actually needs to resize. 1% is the corner case of us resizing the preview page, but even in that case resizing doesn't pose major threat. But I'll optimize it :)

And it's not correct to assume resizing is extremely rare. Hans might be referring to presentations only. However, one of the **main goals** of Vizabi is being portable and mobile friendly. And well, tablets and phones need resize all the time: landscape, portrait, landscape again... There you go, 3 resizes in 1 session.

**Comment by olarosling** [comment]
But wait: this happens rarely, and doesn't have to be fast nor optimized,
and therefor it's not prioritized. Just skip thinking about this
optimization compared to other things, please.

On 8 March 2015 at 23:47, Arthur Camara <notifications@github.com> wrote:

> We ask components to resize whenever page is resized.
>
> Not really. We only ask layout to resize
> <https://github.com/Gapminder/vizabi/blob/develop/src/base/layout.js#L44>
> and, in our case, *only tools* have an instance of base/layout, which
> means they are the ones in control.
>
> But you're right that it can be improved. The solution is for base/layout
> to trigger only if REALLY changes the size of the container, and not simply
> at window resize. In that case it is a minor issue because 99% of times
> that the browser changes size, it's because the container actually needs to
> resize. 1% is the corner case of us resizing the preview page, but even in
> that case resizing doesn't pose major threat. But I'll optimize it :)
>
> And it's not correct to assume resizing is extremely rare. Hans might be
> referring to presentations only. However, one of the *main goals* of
> Vizabi is being portable and mobile friendly. And well, tablets and phones
> need resize all the time: landscape, portrait, landscape again... There you
> go, 3 resizes in 1 session.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gapminder/vizabi/issues/75#issuecomment-77779983>.
>



-- 
*Ola Rosling *twitter@olarosling <https://twitter.com/OlaRosling> + 46 73
838 7778
Director & Co-founder, Gapminder
www.gapminder.org — twitter@gapminder <https://twitter.com/Gapminder> —
facebook/gapminder.org  <https://www.facebook.com/gapminder.org>
