### ISSUE TITLE
Auto-generated "more options" dialog. // All options should be in "more options" in all tools

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#797]
This zoom-feature is not listed under options.
![image](https://cloud.githubusercontent.com/assets/496398/10803729/0b272264-7dc4-11e5-807c-50dfc04dff76.png)

**Comment by jheeffer** [comment]
Need to make a new component which looks at which options are in buttonlist and put those options in the option list

**Comment by angieskazka** [comment]
@arthurcamara1 put your name on it. can you please make a sketch? or if you like we can make it together?

**Comment by arthurcamara1** [comment]
@angieskazka @jheeffer It shouldn't just look at buttonlist because there are things that are *not* in buttonlist that should be in more options.

I suggest we have possible configurations for each button, making it simple to add anything to `more-options`. This way we can also use `more-options` in a more generic way, for all charts (it currently only works well for bubble chart).

Something like:

```javascript
buttons: ['find', 'color', ... 'more-options']
config: {
    'more-options': {
        sections: ['size-advanced', 'color-advanced']
    }
}
```

Such settings could be part of default options or could also be injected by the **tool** itself (in tools/bubblechart/bubblechart.js for instance).

And about the fact that the list becomes too long, we should go with @angieskazka's idea of having accordions in options. Having a long list of unpredictable height is causing problems with the animation and breaking the page.

Here's a mock:

![image](https://cloud.githubusercontent.com/assets/3584238/11208935/5499e3d2-8d1e-11e5-80c2-4bdfb0a79867.png)

**Comment by arthurcamara1** [comment]
Related: https://github.com/Gapminder/vizabi/issues/968

**Comment by angieskazka** [comment]
postponing until #1065 is done

**Comment by angieskazka** [comment]
There is more:
the dialog elements should have 3 profiles: `popup`, `sidebar`, `moreoptions`
(classes applied to different divs in every dialog html)
 
these should allow to use the same dialog but display different parts of it in respective situations
the moreoptions dialog should then be generated for every tool automatically
we can have a config that would tell which dialogs to put in more options
also the buttons which didn't fit in the buttonlist should appear in more options on the top

the questions is: how do we deal with small things like bubble speed slider or presentation checkbox, which are not dialogs on their own, there will be many of these i guess..
