### ISSUE TITLE
v0.8.5_10: “Color” option is missing in the options.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#826]
**SUMMARY:**
1)	“Color” option is missing in the options.
2)	“Bubble size scale bar” is missing in the options.

**SEVERITY:**  Major

**MODULE:**  Bubble Chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  42.0
* MAC / Safari 8.1
* iPad Air 2 iOS(9.1) / Safari 
* Nexus-5 (6.0) / Chrome 
* Nexus 9 (5.0.2) / Chrome 

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/bubblechart.html
2)	“Bubble Chart” page will be loaded.
3)	Click on “Options” icon.
4)	A pop-up of “Options” will display on the screen.
5)	Note that “Color” option and “Bubble size scale” is missing in the pop-up.

**ACTUAL RESULTS:**
“Color” option and “Bubble size scale bar” is missing in the options.

**EXPECTED RESULTS:**
“Color” option and “Bubble size scale bar” should not be missing in the options.

**SCREENSHOT:**

![v0 8 5_10](https://cloud.githubusercontent.com/assets/9950837/10881105/f13f544a-8181-11e5-8859-7b7c25070d36.png)

**Comment by jheeffer** [comment]
Styling should be updated later

**Comment by angieskazka** [comment]
it's not about styling, it's about content

umar was missing “color” from the "more options” menu. i removed color some time ago, because it fully replicates the color dialog that we have anyway. but what if the color button is not visible because it doesn’t fit? should it then be under more options? in that case, should more options include all possible dialogs? that would be a long-long list

and would look very confusing

**Comment by jheeffer** [comment]
Quote from Arthur, paraphrasing Ola

The dev flow of dialogues should follow something like this:
1. We need UI controls for feature X
2. Add the controls to more-options FIRST
3. Is it a useful control for most people? If so, add a specific dialogue for it, simplified with only the most common selectors.

I agree we should in this case redesign (more-)options because in the current form it will grow into something very ugly ; )
