### ISSUE TITLE
Make selected shape dark stroke, show 99.9% of population

### ISSUE THREAD

**Issue by olarosling** [Gapminder/vizabi#854]
![image](https://cloud.githubusercontent.com/assets/496398/10918177/9f69b514-8264-11e5-891b-acb1f11cf11f.png)
Not by pixel

**Comment by angieskazka** [comment]
to show 99.9% of country population is expensive, because it involves calculating areas under the curve

mathematically-correct solution: check each point and cut it if the area to the left/right of the point is too low. requires calculating areas

i suggest a simpler model: more than 0,1% of population ​*at each point*​

cheap solution: check every point, and cut it there if the point area is too low in relation to the population of the country

it becomes size-independent

![image](https://cloud.githubusercontent.com/assets/3648190/10918619/f3f6c6f6-8266-11e5-90de-29134d58e6c8.png)

artifacts:

![image](https://cloud.githubusercontent.com/assets/3648190/10919552/eba18018-826b-11e5-8751-31a782405366.png)
