### ISSUE TITLE
v0.8.8_09: Curves are not shown according to population

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#957]
**SEVERITY:**  Major

**MODULE:** Mountain chart

**Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  43.0
* MAC / Safari 9.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/mountainchart.html
2)	Mountain Chart will be loaded.
3)	Click “Full” under RESPONSIVENESS
4)	Click “Stack”. A small pop up screen is displayed
5)	Select ‘None’ under ‘Chose how to stack mountains’ and click OK
6)	Select the two highest curves
7)	Note that the highest curve is showing “India” instead of “China”

**ACTUAL RESULTS:**
The highest curve is showing “India” instead of “China”

**EXPECTED RESULTS:**
The highest curve should show “China” instead of “India”

**SCREENSHOT:**

![v0 8 8_09](https://cloud.githubusercontent.com/assets/9950837/11181350/32fe8d68-8c83-11e5-9f76-407b7795b125.png)

**Comment by angieskazka** [comment]
it's not a bug, it's a feature:
China curve has a greater area => larger population
China curve is lower than India => higher inequality

Curves on non-stacked view are sorted not by population, but by max height to avoid overlappings as much as possible. That's why india is behind china on the picture 

On stacked view they are sorted by area (population), that's why china is placed on top
